### ISSUE TITLE
index.html problems and update to Apache Spark 2.3

### ISSUE THREAD

**Issue by zroubalik** [radanalyticsio/grafzahl#4]
- patternfly dependencies in index.html need to be updated, the same way it was done for [jgrafzahl](https://github.com/radanalyticsio/jgrafzahl/commit/ac2c3f530f049d66af689c23ea2672929fcd0004#diff-f0bcf93f0276081da8e23f61598bbd47)

- ajax function call doesn't work properly, therefore graph on the web page is not updated when we change the number words to be displayed, same problem like in [jgrafzahl](https://github.com/radanalyticsio/jgrafzahl/commit/668ef2a2d013cd88aa40fd788745cad94bc2e36f)

- on tutorial page https://radanalytics.io/applications/grafzahl  ->  SPARK_OPTIONS need to be fixed to use Spark 2.3.0 in GrafZahl deployment command

**Comment by zroubalik** [comment]
@elmiko you forgot to fix the tutorial page, see the last point from the issue description.

**Comment by elmiko** [comment]
didn't forget, i'm just pulling it together in another patch ;)

i'm going to change the docs on radanalytics.io and the make the grafzahl and jgrafzahl readme's reference that.
